version: '3.8'

services:
    mysql:
        build: ./docker/mysql
        container_name: mysql
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        networks:
            - internal
    php:
        build: ./docker/php-fpm
        container_name: php
        restart: always
        volumes:
            - .:/var/www/symfony
        depends_on:
            - mysql
        networks:
            - internal
    nginx:
        build: ./docker/nginx
        container_name: nginx
        restart: always
        ports:
            - '8081:80'
            - '443:443'
        volumes:
            - .:/var/www/symfony:ro
        depends_on:
            - php
        networks:
            - internal

volumes:
    mysql-data:
        driver: local

networks:
    internal:
        driver: bridge
